site_name: Foundations Guidebook

nav:
    - Home: index.md
    - Instructors: instructors.md
    - Helpers: helpers.md
    - Curriculum Notes: curriculum-notes.md    
    - Tips for Instructors: tips.md
    - Get Involved: getting-involved.md
    - Resources: resources.md
theme:
  name: 'material'
  primary: 'blue'
  accent: 'green'

  logo: 'images/crown-invert.png'
